spring.config.import=optional:file:.env[.properties]

# Application
spring.application.name=smart-campus
server.port=8081

spring.profiles.active=prod

# MySQL (FINAL DATABASE)
spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus
spring.datasource.username=smartcampus
spring.datasource.password=password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

# CORS
app.cors.allowed-origins=http://localhost:3000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=892151900447-qcjbem3rje4kev44i4e22bfvg8sbf1s0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# JWT / Admin
app.jwt.secret=replace-with-a-long-random-secret-at-least-32-characters
app.jwt.expiration-ms=86400000
app.oauth2.redirect-url=http://localhost:3000/oauth/callback
app.admin.email=admin@gmail.com

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
app.upload.dir=uploads/tickets

# Session
server.servlet.session.cookie.same-site=lax
